### ISSUE TITLE
API level 31 checklist

### ISSUE THREAD

**Issue by DDoSolitary** [DDoSolitary/OkcAgent#78]
- [ ] [Foreground service launch restrictions](https://developer.android.com/about/versions/12/foreground-services)
- [ ] `fullBackupContent="true"` deprecated
- [ ] [Pending intents mutability](https://developer.android.com/about/versions/12/behavior-changes-12#pending-intent-mutability)
- [ ] [Notification trampoline restrictions](https://developer.android.com/about/versions/12/behavior-changes-12#notification-trampolines)
